blogs_sql:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: my_blogs
    username: root
    password: 123456
#配置日志
logging:
  level:
    #不同目录下的日志可配置不同级别
    root: info
    com.star: debug
    #采用相对路径方式将日志文件输出到【log/blog-dev.log】
  file:
    name: log/blog-dev.log

#起别名，mapper路径，驼峰命名规则
mybatis:
  type-aliases-package: com.ldf.demo.pojo
  mapper-locations: classpath:com.ldf.demo.mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#配置端口
server:
  port: 80

#jwt
blogs_jwt:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl:  8 # 一天 86400000
    #    admin-ttl: 7200000 # 两小时
    # 设置前端传递过来的令牌名称
    admin-token-name: token