spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: dev
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${blogs_sql.datasource.host}:${blogs_sql.datasource.port}/${blogs_sql.datasource.database}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: ${blogs_sql.datasource.username}
      password: ${blogs_sql.datasource.password}


comment.avatar: /images/avatar.png
message.avatar: /images/avatar.png

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.blogs.entity

#mybatis:
#  mapper-location: classpath:mapper/*.xml


blogs:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: ${blogs_jwt.jwt.admin-secret-key}
    # 设置jwt过期时间
    admin-ttl: ${blogs_jwt.jwt.admin-ttl}
    # 设置前端传递过来的令牌名称
    admin-token-name: ${blogs_jwt.jwt.admin-token-name}

    # 设置jwt签名加密时使用的秘钥
    user-secret-key: ${blogs_jwt.jwt.admin-secret-key}
    # 设置jwt过期时间
    user-ttl: ${blogs_jwt.jwt.admin-ttl}
    # 设置前端传递过来的令牌名称
    user-token-name: ${blogs_jwt.jwt.admin-token-name}